[package]
name = "zr"
version = "0.9.0"
authors = ["Jonathan Dahan <hi@jonathan.is>"]
description = "quick, simple zsh package manager"
readme = "readme.md"
keywords = ["zsh", "package", "manager", "cli"]
license = "MPL-2.0"
repository = "https://github.com/jedahan/zr.git"
edition = "2018"

[badges]
travis-ci = { repository = "jedahan/zr" }

[dependencies]
git2 = "0.10.2"
directories = "2.0.2"
url = "2.1.0"
git2_credentials = "0.3.2"

[profile.release]
lto = true
codegen-units = 1
incremental = false
